# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'leonardoWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.uic import loadUi


class Ui_liveSupport(object):
    def __init__(self):
        super(Ui_liveSupport, self).__init__()
        loadUi("live_support.ui",self)